name: Update Parent Repository
on:
  push:
    branches: [ main ]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ifNotErrorRun/blog
          token: ${{ secrets.PAT }}
          submodules: recursive
      - name: Merge submodule updates
        run: |
          git submodule update --remote --merge --allow-unrelated-histories
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Auto-update submodules" || true
          git push
        shell: bash
